# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JouryStore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FSPagerView' , '0.8.2'
  pod 'SwifterSwift' , '5.1.0'
  pod 'IQKeyboardManagerSwift', '6.2.1'
  pod 'DZNEmptyDataSet',:git => 'https://gitlab.com/mja050/dznemptydataset.git'
  pod 'FDTake', :git => 'https://gitlab.com/mja050/fdtake.git'
  pod 'Presentr', '1.9'
  pod 'SwiftyJSON', '5.0.0'
  pod 'SwiftPullToRefresh'
  pod 'SVProgressHUD'
  pod 'SwiftyOnboard'
  pod 'UINavigationBar+Addition'
  pod 'Alamofire', '~> 5.0.0-rc.2'
  pod 'SDWebImage', '5.6.0'
  pod 'AlertsPickers',:git => "https://gitlab.com/mja050/AlertsPickersPod.git"
  pod 'RangeSeekSlider', '1.8.0'
  pod 'PhoneNumberKit', '3.3.3'

  
  # Pods for JouryStore
  
  target 'JouryStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
end
